import type { Dictionary } from '../types';

const it: Dictionary = {
  nav: { inicio: 'Home', esencia: 'La nostra essenza', familia: 'Famiglia', soluciones: 'Soluzioni', eleccion: 'Perché sceglierci', impulsamos: 'Cosa promuoviamo', marcas: 'Marchi', atencion: 'Assistenza', contacto: 'Contatti', solicitarCotizacion: 'Richiedi un preventivo', portalClientes: 'Area clienti', iniciarSesion: 'Accedi', crearCuenta: 'Crea account', miCuenta: 'Il mio account', abrirMenu: 'Apri menu', cerrarMenu: 'Chiudi menu', navegacionPrincipal: 'Navigazione principale' },
  languageSelector: { label: 'Seleziona lingua' },
  common: { close: 'Chiudi', closeProfileAria: 'Chiudi profilo', previous: 'Precedente', next: 'Successivo', loading: 'Caricamento...' },
  cookies: { ariaLabel: 'Preferenze sui cookie', text: 'Gentile visitatore, utilizziamo i cookie per migliorare la tua esperienza di navigazione. Continuando a utilizzare questo sito, accetti l\'uso dei cookie. Puoi consultare la nostra {privacidad} e la nostra {cookies}.', privacyLink: 'Informativa sulla Privacy', cookiesLink: 'Politica sui Cookie', accept: 'Accetta', reject: 'Rifiuta' },
  account: { portalTitle: 'Area clienti', loginTitle: 'Accedi', registerTitle: 'Crea il tuo account', loginIntro: 'Accedi al tuo account Distribuidora Var San.', registerIntro: 'Registrati per accedere all\'area clienti Var San.', tabLogin: 'Accedi', tabRegister: 'Crea account', fieldName: 'Nome', fieldNamePlaceholder: 'Il tuo nome', fieldCompany: 'Azienda', fieldCompanyPlaceholder: 'Nome della tua azienda', fieldEmail: 'E-mail', fieldEmailPlaceholder: 'email@azienda.com', fieldPassword: 'Password', fieldPasswordPlaceholderLogin: 'La tua password', fieldPasswordPlaceholderRegister: 'Minimo 6 caratteri', fieldConfirmPassword: 'Conferma password', fieldConfirmPasswordPlaceholder: 'Ripeti la password', submitLogin: 'Accedi', submitRegister: 'Crea account', continueWithGoogle: 'Continua con Google', secureAccessNote: 'Accesso sicuro per i clienti Var San tramite Firebase Authentication e Firestore.', passwordMismatch: 'Le password non coincidono.', accountCreated: 'Account creato correttamente.', loginSuccess: 'Accesso effettuato correttamente.', errorEmailInUse: 'Questa e-mail ha già un account.', errorWeakPassword: 'La password deve contenere almeno 6 caratteri.', errorInvalidEmail: 'L\'indirizzo e-mail non è valido.', errorInvalidCredential: 'E-mail o password non corretti.', errorTooManyRequests: 'Troppi tentativi. Attendi un momento e riprova.', errorGeneric: 'Firebase: {code} — {message}', errorGoogleSignIn: 'Impossibile accedere con Google.', errorSaveProfile: 'Impossibile salvare il profilo.' },
  portal: { eyebrow: 'Area clienti', welcome: 'Benvenuto{name}.', intro: 'La tua sessione è collegata a Firebase e i tuoi dati cliente vengono caricati da Firestore.', fieldNameLabel: 'Nome', fieldEmailLabel: 'E-mail', fieldCompanyLabel: 'Azienda', defaultClientName: 'Cliente Var San', notSpecified: 'Non specificata', notAvailable: 'Non disponibile', myProfile: 'Il mio profilo', logOut: 'Esci', closePortal: 'Chiudi area clienti', profileHeading: 'Dati del cliente', profileIntro: 'Le modifiche vengono salvate nel tuo profilo Firestore.', saveChanges: 'Salva modifiche' },
  hero: { eyebrow: 'Marchi leader · Qualità garantita', titleLead: 'Soluzioni per la ', titleHighlight: 'pulizia e protezione', titleTail: ' della tua azienda.', textBefore: 'Oltre ', textAfter: ' selezionati con cura per aziende, industrie, negozi e istituzioni.', productsHighlight: '1000 prodotti', extra: 'In Distribuidora Var San crediamo che un buon fornitore non si limiti a consegnare prodotti, ma offra fiducia, qualità e soluzioni per la crescita della tua azienda.', exploreSolutions: 'Esplora le soluzioni', requestQuote: 'Richiedi un preventivo', imageAlt: 'Forniture professionali di pulizia e protezione', captionEyebrow: 'Il tuo alleato', captionText: 'in pulizia, igiene e protezione.', statTitle: '1000+ Prodotti', statSubtitle: 'Tutto in un unico posto.' },
  essence: { eyebrow: 'La nostra essenza', title: 'I valori che ci rappresentano.', lede: 'Più che distribuire prodotti, costruiamo relazioni basate su qualità, impegno e fiducia.', values: { quality: { title: 'Qualità', description: 'Selezioniamo attentamente ogni prodotto per offrire soluzioni affidabili e dalle prestazioni elevate.' }, closeness: { title: 'Vicinanza', description: 'Forniamo attenzione personalizzata e supporto durante ogni ordine.' }, commitment: { title: 'Impegno', description: 'Rispondiamo con responsabilità, puntualità e un servizio pensato per la tua azienda.' }, trust: { title: 'Fiducia', description: 'Costruiamo relazioni durature basate su onestà, appoggio e risultati coerenti.' } } },
  family: { eyebrow: 'Fai parte della famiglia Var San', title: 'Cresciamo quando i nostri clienti crescono.', subtitle: 'Esperienza Var San', label: 'Esperienza Var San', ariaLabel: 'Visualizza esperienza {slide}', slides: [['FIDUCIA', 'Oggi serviamo dalle piccole attività alle aziende che cercano un fornitore affidabile per crescere.'], ['APPOGGIO', 'Siamo presenti dal primo preventivo fino alla consegna di ogni ordine.'], ['RELAZIONE', 'Non cerchiamo una sola vendita. Cerchiamo di costruire relazioni durature con ogni cliente.'], ['CRESCITA', 'Quando i nostri clienti crescono, sappiamo che stiamo facendo bene il nostro lavoro.'], ['BENVENUTO', 'Grazie per aver considerato Distribuidora Var San come parte della tua azienda.']] },
  solutions: { eyebrow: 'Le nostre soluzioni', title: 'Trova la soluzione ideale per la tua azienda', lede: 'Il pulsante "Visualizza catalogo completo" aprirà il PDF della linea selezionata. Ogni categoria (Sicurezza industriale e Linea medica) ha il suo catalogo indipendente.', catalogPart1: 'Il pulsante "Visualizza catalogo completo" aprirà il PDF della linea selezionata. Ogni categoria (', catalogStrongPart: 'Sicurezza industriale e Linea medica', catalogPart2: ') ha il suo catalogo indipendente.', catalogPart3: '', tabListLabel: 'Linee di prodotti', categoriesLabel: 'Categorie', categoriesScreenReader: 'Categorie di prodotti', previousCategory: 'Categoria precedente', nextCategory: 'Categoria successiva', fullCatalog: 'Visualizza catalogo completo' },
  whyChoose: { eyebrow: 'Perché sceglierci?', title: 'Perché scegliere Distribuidora Var San?', lede: 'Più che un fornitore, siamo il partner che spinge la crescita della tua azienda.', ariaLabel: 'Motivi per sceglierci', reasonLabel: 'Visualizza motivo {number}', previousReason: 'Motivo precedente', nextReason: 'Prossimo motivo', reasons: [['Inventario esteso', 'Migliaia di prodotti disponibili per rispondere rapidamente alle esigenze di diversi settori.'], ['Marchi riconosciuti', 'Lavoriamo con produttori prestigiosi per offrire soluzioni affidabili e ad alte prestazioni.'], ['Attenzione personalizzata', 'Ascoltiamo le esigenze di ogni cliente per fornire consulenza e soluzioni su misura.'], ['Consegne affidabili', 'Coordiniamo ogni ordine con impegno affinché tu riceva i tuoi prodotti in tempo.'], ['Soluzioni complete', 'Dalla sicurezza industriale alla linea medica, riuniamo tutto ciò di cui la tua azienda ha bisogno in un unico posto.'], ['Impegno a lungo termine', 'Cerchiamo di costruire relazioni durature basate su fiducia, servizio e risultati.']] },
  sectors: { eyebrow: 'Settori che promuoviamo', title: 'Soluzioni specializzate per aziende ', titleEmphasis: 'di diversi settori.', names: ['Aziende', 'Uffici', 'Negozi', 'Industrie', 'Scuole', 'Ospedali e Cliniche', 'Ristoranti', 'Alberghi', 'Istituzioni', 'Aziende in generale'] },
  brands: { eyebrow: 'Marchi', title: 'Marchi con cui lavoriamo', lede: 'Distribuiamo prodotti autentici di produttori riconosciuti per qualità e sicurezza.', distributed: 'Marchio distribuito' },
  process: { eyebrow: 'Processo di Servizio', title: 'Lavorare con noi è così ', titleEmphasis: 'semplice', steps: [['1', 'Richiedi il tuo preventivo', 'Contattaci via WhatsApp, telefono o e-mail e condividi i prodotti di cui hai bisogno.'], ['2', 'Prepariamo la tua proposta', 'Esaminiamo la tua richiesta e prepariamo un preventivo personalizzato secondo i tuoi requisiti.'], ['3', 'Coordiniamo il tuo ordine', 'Una volta accettato il preventivo, coordiniamo con te la consegna o il ritiro dei prodotti nella data concordata.']] },
  contact: { eyebrow: 'Contattaci', title: 'Richiedi informazioni o un ', titleEmphasis: 'preventivo', lede: 'Lasciaci i tuoi dati e ti contatteremo per gestire la tua richiesta.', email: 'E-mail', phone: 'Telefono e WhatsApp', attention: 'Assistenza', attentionInfo: 'Aziende, industrie, negozi e istituzioni', form: { nameLabel: 'Nome', emailLabel: 'E-mail', companyLabel: 'Azienda', messageLabel: 'Messaggio', submitButton: 'Invia richiesta' } },
  newsletter: { title: 'Iscriviti!', lede: 'Registrati alla nostra newsletter e sii il primo a conoscere i nostri lanci e promozioni', placeholder: 'E-mail', ariaLabelInput: 'E-mail per iscriverti alla nostra newsletter', ariaLabelButton: 'Iscriviti alla newsletter', alreadySubscribed: 'Questa e-mail è già iscritta alla nostra newsletter.', subscriptionSuccess: 'Perfetto! Ti sei iscritto con successo.', subscriptionError: 'Non abbiamo potuto completare la tua iscrizione. Riprova.', networkError: 'Non abbiamo potuto connetterci al server. Riprova tra pochi secondi.' },
  chatbot: { openButtonLabel: 'Apri chatbot', closeButtonLabel: 'Chiudi chatbot', headerTitle: 'Assistente Var San', headerSubtitle: 'Informazioni su prodotti e contatti', greeting: 'Ciao. Sono l\'Assistente Var San. Posso aiutarti con le nostre linee di prodotti, cataloghi, copertura di consegna e contatti. Come possiamo aiutarti?', inputPlaceholder: 'Scrivi la tua richiesta (Invio per inviare, Maiusc+Invio per andare a capo)', inputAriaLabel: 'Richiesta per l\'assistente', sendButtonLabel: 'Invia richiesta', quickProducts: 'Che prodotti offrite?', quickQuote: 'Richiedi un preventivo', quickSupport: 'Assistenza', quickContact: 'Come posso contattarvi?', loadingMessage: 'Sto scrivendo...', errorMessage: 'Non siamo riusciti a elaborare il tuo messaggio. Riprova tra pochi secondi.' },
  footer: { navigationHeading: 'Navigazione', contactHeading: 'Contatti', requestQuote: 'Richiedi un preventivo', rightsReserved: '© {year} Distribuidora Var San. Tutti i diritti riservati. |', tagline: 'Soluzioni di pulizia e protezione per la tua azienda.', privacyNotice: 'Informativa sulla Privacy', cookiesPolicy: 'Politica sui Cookie', termsAndConditions: 'Termini e Condizioni', brandDescription: 'Soluzioni di pulizia e protezione', footerTagline: 'Soluzioni di pulizia e protezione per la tua azienda. Impegnati a fornire soluzioni affidabili in pulizia, manutenzione e protezione per aziende, negozi e istituzioni.' },
  splash: { ariaLabel: 'Caricamento di Distribuidora Var San', tagline: 'Qualità e fiducia in ogni fornitura.' },
};

export default it;
