import type { Dictionary } from '../types';

const ko: Dictionary = {
  nav: { inicio: '홈', esencia: '브랜드 소개', familia: '우리 팀', soluciones: '솔루션', eleccion: '선택 이유', impulsamos: '우리가 추구하는 것', marcas: '브랜드', atencion: '고객 지원', contacto: '문의', solicitarCotizacion: '견적 요청', portalClientes: '고객 포털', iniciarSesion: '로그인', crearCuenta: '계정 만들기', miCuenta: '내 계정', abrirMenu: '메뉴 열기', cerrarMenu: '메뉴 닫기', navegacionPrincipal: '주 메뉴' },
  languageSelector: { label: '언어 선택' },
  common: { close: '닫기', closeProfileAria: '프로필 닫기', previous: '이전', next: '다음', loading: '로딩 중...' },
  cookies: { ariaLabel: '쿠키 환경설정', text: '방문해 주셔서 감사합니다. 저희는 더 나은 이용 경험을 제공하기 위해 쿠키를 사용합니다. 사이트를 계속 이용하시면 쿠키 사용에 동의하는 것으로 간주됩니다. {privacidad} 및 {cookies}를 확인하실 수 있습니다.', privacyLink: '개인정보 처리방침', cookiesLink: '쿠키 정책', accept: '수락', reject: '거부' },
  account: { portalTitle: '고객 포털', loginTitle: '로그인', registerTitle: '계정 만들기', loginIntro: 'Distribuidora Var San 계정에 접속하세요.', registerIntro: 'Var San 고객 포털을 이용하려면 가입하세요.', tabLogin: '로그인', tabRegister: '계정 만들기', fieldName: '이름', fieldNamePlaceholder: '이름을 입력하세요', fieldCompany: '회사', fieldCompanyPlaceholder: '회사명을 입력하세요', fieldEmail: '이메일', fieldEmailPlaceholder: 'email@company.com', fieldPassword: '비밀번호', fieldPasswordPlaceholderLogin: '비밀번호를 입력하세요', fieldPasswordPlaceholderRegister: '최소 6자 이상', fieldConfirmPassword: '비밀번호 확인', fieldConfirmPasswordPlaceholder: '비밀번호를 다시 입력하세요', submitLogin: '로그인', submitRegister: '계정 만들기', continueWithGoogle: 'Google 계정으로 계속하기', secureAccessNote: 'Var San 고객은 Firebase Authentication과 Firestore를 통해 안전하게 접속합니다.', passwordMismatch: '비밀번호가 일치하지 않습니다.', accountCreated: '계정이 성공적으로 생성되었습니다.', loginSuccess: '로그인되었습니다.', errorEmailInUse: '이미 해당 이메일로 가입된 계정이 있습니다.', errorWeakPassword: '비밀번호는 최소 6자 이상이어야 합니다.', errorInvalidEmail: '유효하지 않은 이메일 주소입니다.', errorInvalidCredential: '이메일 또는 비밀번호가 올바르지 않습니다.', errorTooManyRequests: '시도 횟수가 너무 많습니다. 잠시 후 다시 시도해 주세요.', errorGeneric: 'Firebase: {code} — {message}', errorGoogleSignIn: 'Google로 로그인할 수 없습니다.', errorSaveProfile: '프로필을 저장할 수 없습니다.' },
  portal: { eyebrow: '고객 포털', welcome: '환영합니다{name}.', intro: '현재 세션은 Firebase에 연결되어 있으며, 고객 정보는 Firestore에서 불러옵니다.', fieldNameLabel: '이름', fieldEmailLabel: '이메일', fieldCompanyLabel: '회사', defaultClientName: 'Var San 고객', notSpecified: '미입력', notAvailable: '정보 없음', myProfile: '내 프로필', logOut: '로그아웃', closePortal: '포털 닫기', profileHeading: '고객 정보', profileIntro: '변경 사항은 Firestore 프로필에 저장됩니다.', saveChanges: '변경 사항 저장', sessionsTitle: '기기 및 활성 세션', sessionsSubtitle: '계정에 연결된 기기를 관리합니다.', currentDeviceBadge: '이 기기 (현재 세션)', lastActiveLabel: '최근 활동', locationLabel: '위치 / IP', revokeSession: '로그아웃', revokeAllOthers: '다른 모든 기기에서 로그아웃', confirmRevokeAll: '다른 모든 기기에서 로그아웃하시겠습니까?', noActiveSessions: '등록된 다른 활성 세션이 없습니다.', sessionRevokedSuccess: '원격 세션이 성공적으로 로그아웃되었습니다.', sessionsRevokedAllSuccess: '다른 모든 활성 세션에서 로그아웃되었습니다.', loadingSessions: '활성 세션 불러오는 중...', refreshSessions: '세션 새로고침' },
  hero: { eyebrow: '선도 브랜드 · 품질 보증', titleLead: '귀사를 위한 ', titleHighlight: '청소 및 보호', titleTail: ' 솔루션.', textBefore: '', textAfter: ' 이상 엄선하여 기업, 산업, 상점 및 기관에 제공합니다.', productsHighlight: '1000개 제품', extra: 'Distribuidora Var San은 좋은 공급업체란 단순히 제품을 전달하는 것이 아니라 신뢰, 품질, 그리고 귀사의 성장을 위한 솔루션을 제공하는 것이라고 믿습니다.', exploreSolutions: '솔루션 살펴보기', requestQuote: '견적 요청', imageAlt: '전문 청소 및 보호 용품', captionEyebrow: '믿을 수 있는 파트너', captionText: '청소, 위생 및 보호 분야에서.', statTitle: '1000개 이상 제품', statSubtitle: '한 곳에서 모두 해결.' },
  essence: { eyebrow: '우리의 정체성', title: '우리를 대표하는 가치들.', lede: '제품 배포를 넘어 품질, 약속, 신뢰에 기반한 관계를 구축합니다.', values: { quality: { title: '품질', description: '신뢰할 수 있고 뛰어난 성능의 솔루션을 제공하기 위해 각 제품을 신중히 선별합니다.' }, closeness: { title: '근접성', description: '각 주문 전반에 걸쳐 개인화된 주의와 지원을 제공합니다.' }, commitment: { title: '약속', description: '귀사를 위해 설계된 책임감 있고 시기 적절한 서비스로 대응합니다.' }, trust: { title: '신뢰', description: '성실함, 지원, 일관된 결과에 기반한 지속적인 관계를 구축합니다.' } } },
  family: { eyebrow: 'Var San 가족의 일원이 되세요', title: '고객이 성장할 때 우리도 성장합니다.', subtitle: 'Var San 경험', label: 'Var San 경험', ariaLabel: '{slide} 경험 보기', slides: [['신뢰', '현재 소규모 비즈니스부터 신뢰할 수 있는 공급업체를 찾는 회사까지 다양한 고객을 섬기고 있습니다.'], ['지원', '첫 견적부터 모든 배송까지 항상 함께합니다.'], ['관계', '우리는 단 하나의 판매를 원하지 않습니다. 각 고객과 오랜 관계를 구축하고 싶습니다.'], ['성장', '우리 고객이 성장할 때, 우리는 제대로 일하고 있다는 것을 압니다.'], ['환영', 'Distribuidora Var San을 귀사의 일부로 생각해 주셔서 감사합니다.']] },
  solutions: { eyebrow: '우리의 솔루션', title: '귀사에 맞는 솔루션을 찾으세요', lede: '\"전체 카탈로그 보기\" 버튼은 선택한 제품군의 PDF를 열 것입니다. 각 카테고리(산업 안전 및 의료용품)는 자체 카탈로그를 가지고 있습니다.', catalogPart1: '\"전체 카탈로그 보기\" 버튼은 선택한 제품군의 PDF를 열 것입니다. 각 카테고리(', catalogStrongPart: '산업 안전 및 의료용품', catalogPart2: ')는 자체 카탈로그를 가지고 있습니다.', catalogPart3: '', tabListLabel: '제품 라인', categoriesLabel: '카테고리', categoriesScreenReader: '제품 카테고리', previousCategory: '이전 카테고리', nextCategory: '다음 카테고리', fullCatalog: '전체 카탈로그 보기' },
  whyChoose: { eyebrow: '저희를 선택하는 이유', title: 'Distribuidora Var San을 선택하는 이유', lede: '공급업체 이상으로, 우리는 귀사의 성장을 이끄는 파트너입니다.', ariaLabel: '저희를 선택해야 할 이유', reasonLabel: '이유 {number} 보기', previousReason: '이전 이유', nextReason: '다음 이유', reasons: [['광범위한 재고', '다양한 부문의 필요를 빠르게 충족하기 위해 수천 개의 제품을 보유하고 있습니다.'], ['인정받은 브랜드', '신뢰할 수 있고 뛰어난 솔루션을 제공하기 위해 명망 있는 제조업체와 협력합니다.'], ['맞춤형 지원', '각 고객의 필요를 경청하여 맞춤형 조언과 솔루션을 제공합니다.'], ['신뢰할 수 있는 배송', '각 주문을 책임감 있게 조율하여 시간 내에 제품을 받을 수 있도록 합니다.'], ['통합 솔루션', '산업 안전부터 의료용품까지, 귀사가 필요한 모든 것을 한 곳에서 제공합니다.'], ['장기적 약속', '신뢰, 서비스, 결과에 기반한 지속적인 관계를 구축하고자 합니다.']] },
  sectors: { eyebrow: '우리가 지원하는 산업', title: '다양한 산업의 기업을 위한 ', titleEmphasis: '맞춤형 솔루션.', names: ['기업', '사무실', '상점', '산업', '학교', '병원 및 클리닉', '음식점', '호텔', '기관', '일반 비즈니스'] },
  brands: { eyebrow: '브랜드', title: '저희가 협력하는 브랜드', lede: '품질과 안전으로 인정받은 제조업체의 정품을 배포합니다.', distributed: '배포 중인 브랜드' },
  process: { eyebrow: '서비스 절차', title: '저희와 함께 일하는 것은 이렇게 ', titleEmphasis: '간단합니다', steps: [['1', '견적을 요청하세요', 'WhatsApp, 전화 또는 이메일로 저희에게 연락하고 필요한 제품을 알려주세요.'], ['2', '제안을 준비합니다', '요청을 검토하고 요구사항에 맞는 맞춤형 견적을 준비합니다.'], ['3', '주문을 조율합니다', '견적을 수락한 후, 합의된 날짜에 제품을 배송하거나 픽업하도록 조율합니다.']] },
  contact: { eyebrow: '저희에게 연락하세요', title: '정보나 ', titleEmphasis: '견적을 요청하세요', lede: '정보를 남겨주시면 요청을 처리하기 위해 연락드리겠습니다.', email: '이메일', phone: '전화 및 WhatsApp', attention: '지원', attentionInfo: '기업, 산업, 상점 및 기관', form: { nameLabel: '이름', emailLabel: '이메일', companyLabel: '회사', messageLabel: '메시지', submitButton: '요청 전송' } },
  newsletter: { title: '구독하세요!', lede: '뉴스레터에 등록하고 새로운 출시와 프로모션을 가장 먼저 알아보세요', placeholder: '이메일 주소', ariaLabelInput: '뉴스레터 구독을 위한 이메일 주소', ariaLabelButton: '뉴스레터 구독', alreadySubscribed: '이 이메일은 이미 뉴스레터에 구독되어 있습니다.', subscriptionSuccess: '완료! 성공적으로 구독되었습니다.', subscriptionError: '구독을 완료할 수 없었습니다. 다시 시도해 주세요.', networkError: '서버에 연결할 수 없습니다. 잠시 후 다시 시도해 주세요.' },
  chatbot: { openButtonLabel: '챗봇 열기', closeButtonLabel: '챗봇 닫기', headerTitle: 'Var San 어시스턴트', headerSubtitle: '제품 및 문의 안내', greeting: '안녕하세요. Var San 어시스턴트입니다. 제품 라인, 카탈로그, 배송 가능 지역, 문의 방법에 대해 안내해 드릴 수 있습니다. 무엇을 도와드릴까요?', inputPlaceholder: '문의 내용을 입력하세요 (Enter 전송, Shift+Enter 줄바꿈)', inputAriaLabel: '어시스턴트에게 보낼 메시지', sendButtonLabel: '메시지 보내기', quickProducts: '어떤 제품을 취급하시나요?', quickQuote: '견적 요청', quickSupport: '고객 지원', quickContact: '어떻게 연락드릴 수 있나요?', loadingMessage: '입력 중...', errorMessage: '메시지를 처리하지 못했습니다. 잠시 후 다시 시도해 주세요.' },
  footer: { navigationHeading: '메뉴', contactHeading: '문의처', requestQuote: '견적 요청', rightsReserved: '© {year} Distribuidora Var San. 모든 권리 보유. |', tagline: '귀사를 위한 청소 및 보호 솔루션.', privacyNotice: '개인정보 처리방침', cookiesPolicy: '쿠키 정책', termsAndConditions: '이용 약관', brandDescription: '청소 및 보호 솔루션', footerTagline: '귀사를 위한 청소 및 보호 솔루션. 기업, 상점 및 기관을 위한 청소, 유지보수 및 보호 분야의 신뢰할 수 있는 솔루션을 제공하기 위해 최선을 다합니다.' },
  splash: { ariaLabel: 'Distribuidora Var San 로딩 중', tagline: '모든 공급에 담긴 품질과 신뢰.' },
};

export default ko;
