import type { Dictionary } from '../types';

const pt: Dictionary = {
  nav: { inicio: 'Início', esencia: 'Nossa essência', familia: 'Família', soluciones: 'Soluções', eleccion: 'Por que nos escolher', impulsamos: 'Impulsionamos', marcas: 'Marcas', atencion: 'Atendimento', contacto: 'Contato', solicitarCotizacion: 'Solicitar orçamento', portalClientes: 'Portal do cliente', iniciarSesion: 'Entrar', crearCuenta: 'Criar conta', miCuenta: 'Minha conta', abrirMenu: 'Abrir menu', cerrarMenu: 'Fechar menu', navegacionPrincipal: 'Navegação principal' },
  languageSelector: { label: 'Selecionar idioma' },
  common: { close: 'Fechar', closeProfileAria: 'Fechar perfil', previous: 'Anterior', next: 'Próximo', loading: 'Carregando...' },
  cookies: { ariaLabel: 'Preferências de cookies', text: 'Caro visitante, utilizamos cookies para melhorar sua experiência de navegação. Ao continuar a usar este site, você aceita o uso de cookies. Você pode consultar nossa {privacidad} e nossa {cookies}.', privacyLink: 'Política de Privacidade', cookiesLink: 'Política de Cookies', accept: 'Aceitar', reject: 'Recusar' },
  account: { portalTitle: 'Portal do cliente', loginTitle: 'Entre na sua conta', registerTitle: 'Crie sua conta', loginIntro: 'Acesse sua conta Distribuidora Var San.', registerIntro: 'Cadastre-se para acessar o portal do cliente Var San.', tabLogin: 'Entrar', tabRegister: 'Criar conta', fieldName: 'Nome', fieldNamePlaceholder: 'Seu nome', fieldCompany: 'Empresa', fieldCompanyPlaceholder: 'Nome da sua empresa', fieldEmail: 'E-mail', fieldEmailPlaceholder: 'email@empresa.com', fieldPassword: 'Senha', fieldPasswordPlaceholderLogin: 'Sua senha', fieldPasswordPlaceholderRegister: 'Mínimo de 6 caracteres', fieldConfirmPassword: 'Confirmar senha', fieldConfirmPasswordPlaceholder: 'Repita sua senha', submitLogin: 'Entrar', submitRegister: 'Criar conta', continueWithGoogle: 'Continuar com o Google', secureAccessNote: 'Acesso seguro para clientes Var San via Firebase Authentication e Firestore.', passwordMismatch: 'As senhas não coincidem.', accountCreated: 'Conta criada com sucesso.', loginSuccess: 'Sessão iniciada com sucesso.', errorEmailInUse: 'Este e-mail já possui uma conta.', errorWeakPassword: 'A senha deve ter pelo menos 6 caracteres.', errorInvalidEmail: 'O e-mail não é válido.', errorInvalidCredential: 'E-mail ou senha incorretos.', errorTooManyRequests: 'Muitas tentativas. Aguarde um momento e tente novamente.', errorGeneric: 'Firebase: {code} — {message}', errorGoogleSignIn: 'Não foi possível entrar com o Google.', errorSaveProfile: 'Não foi possível salvar o perfil.' },
  portal: { eyebrow: 'Portal do cliente', welcome: 'Bem-vindo{name}.', intro: 'Sua sessão está conectada ao Firebase e seus dados de cliente são carregados do Firestore.', fieldNameLabel: 'Nome', fieldEmailLabel: 'E-mail', fieldCompanyLabel: 'Empresa', defaultClientName: 'Cliente Var San', notSpecified: 'Não especificada', notAvailable: 'Não disponível', myProfile: 'Meu perfil', logOut: 'Sair', closePortal: 'Fechar portal', profileHeading: 'Dados do cliente', profileIntro: 'As alterações são salvas no seu perfil do Firestore.', saveChanges: 'Salvar alterações', sessionsTitle: 'Dispositivos e sessões ativas', sessionsSubtitle: 'Gerencie os dispositivos conectados à sua conta.', currentDeviceBadge: 'Este dispositivo (Sessão atual)', lastActiveLabel: 'Última atividade', locationLabel: 'Localização / IP', revokeSession: 'Desconectar', revokeAllOthers: 'Desconectar todos os outros dispositivos', confirmRevokeAll: 'Deseja desconectar todos os outros dispositivos?', noActiveSessions: 'Nenhuma outra sessão ativa registrada.', sessionRevokedSuccess: 'Sessão remota desconectada com sucesso.', sessionsRevokedAllSuccess: 'Todas as outras sessões ativas foram desconectadas.', loadingSessions: 'Carregando sessões ativas...', refreshSessions: 'Atualizar sessões' },
  hero: { eyebrow: 'Marcas líderes · Qualidade garantida', titleLead: 'Soluções em ', titleHighlight: 'limpeza e proteção', titleTail: ' para sua empresa.', textBefore: 'Mais de ', textAfter: ' cuidadosamente selecionados para empresas, indústrias, comércios e instituições.', productsHighlight: '1000 produtos', extra: 'Na Distribuidora Var San acreditamos que um bom fornecedor não apenas entrega produtos; ele traz confiança, qualidade e soluções para o crescimento da sua empresa.', exploreSolutions: 'Explorar soluções', requestQuote: 'Solicitar orçamento', imageAlt: 'Suprimentos profissionais de limpeza e proteção', captionEyebrow: 'Seu aliado', captionText: 'em limpeza, higiene e proteção.', statTitle: '1000+ Produtos', statSubtitle: 'Tudo em um só lugar.' },
  essence: { eyebrow: 'Nossa essência', title: 'Os valores que nos representam.', lede: 'Mais que distribuir produtos, construímos relacionamentos baseados em qualidade, compromisso e confiança.', values: { quality: { title: 'Qualidade', description: 'Selecionamos cuidadosamente cada produto para oferecer soluções confiáveis e de alto desempenho.' }, closeness: { title: 'Proximidade', description: 'Proporcionamos atenção personalizada e acompanhamento durante cada pedido.' }, commitment: { title: 'Compromisso', description: 'Respondemos com responsabilidade, pontualidade e um serviço pensado para sua empresa.' }, trust: { title: 'Confiança', description: 'Construímos relacionamentos duradouros baseados em honestidade, respaldo e resultados consistentes.' } } },
  family: { eyebrow: 'Faça parte da família Var San', title: 'Crescemos quando nossos clientes crescem.', subtitle: 'Experiência Var San', label: 'Experiência Var San', ariaLabel: 'Ver experiência {slide}', slides: [['CONFIANÇA', 'Hoje atendemos desde pequenos negócios até empresas que buscam um fornecedor confiável para crescer.'], ['RESPALDO', 'Estamos presentes desde a primeira cotação até a entrega de cada pedido.'], ['RELAÇÃO', 'Não buscamos uma única venda. Buscamos construir relacionamentos duradouros com cada cliente.'], ['CRESCIMENTO', 'Quando nossos clientes crescem, sabemos que estamos fazendo bem nosso trabalho.'], ['BEM-VINDO', 'Obrigado por considerar Distribuidora Var San como parte de sua empresa.']] },
  solutions: { eyebrow: 'Nossas soluções', title: 'Encontre a solução ideal para sua empresa', lede: 'O botão "Consultar catálogo completo" abrirá o PDF da linha selecionada. Cada categoria (Segurança Industrial e Linha Médica) possui seu próprio catálogo independente.', catalogPart1: 'O botão "Consultar catálogo completo" abrirá o PDF da linha selecionada. Cada categoria (', catalogStrongPart: 'Segurança Industrial e Linha Médica', catalogPart2: ') possui seu próprio catálogo independente.', catalogPart3: '', tabListLabel: 'Linhas de produtos', categoriesLabel: 'Categorias', categoriesScreenReader: 'Categorias de produtos', previousCategory: 'Categoria anterior', nextCategory: 'Próxima categoria', fullCatalog: 'Consultar catálogo completo' },
  whyChoose: { eyebrow: 'Por que nos escolher?', title: 'Por que escolher Distribuidora Var San?', lede: 'Mais que um fornecedor, somos o aliado que impulsa o crescimento de sua empresa.', ariaLabel: 'Razões para nos escolher', reasonLabel: 'Ver motivo {number}', previousReason: 'Razão anterior', nextReason: 'Próxima razão', reasons: [['Amplo inventário', 'Milhares de produtos disponíveis para responder rapidamente às necessidades de diferentes setores.'], ['Marcas reconhecidas', 'Trabalhamos com fabricantes de prestígio para oferecer soluções confiáveis e de alto desempenho.'], ['Atenção personalizada', 'Ouvimos as necessidades de cada cliente para fornecer consultoria e soluções personalizadas.'], ['Entregas confiáveis', 'Coordenamos cada pedido com compromisso para que você receba seus produtos no prazo.'], ['Soluções integrais', 'De segurança industrial a linha médica, reunimos tudo o que sua empresa precisa em um só lugar.'], ['Compromisso a longo prazo', 'Buscamos construir relacionamentos duradouros baseados em confiança, serviço e resultados.']] },
  sectors: { eyebrow: 'Setores que impulsionamos', title: 'Soluções especializadas para empresas ', titleEmphasis: 'de diferentes setores.', names: ['Empresas', 'Escritórios', 'Comércios', 'Indústrias', 'Escolas', 'Hospitais e Clínicas', 'Restaurantes', 'Hotéis', 'Instituições', 'Negócios em geral'] },
  brands: { eyebrow: 'Marcas', title: 'Marcas com as quais trabalhamos', lede: 'Distribuímos produtos originais de fabricantes reconhecidos por sua qualidade e segurança.', distributed: 'Marca distribuída' },
  process: { eyebrow: 'Processo de Atendimento', title: 'Trabalhar conosco é tão ', titleEmphasis: 'simples', steps: [['1', 'Solicite seu orçamento', 'Entre em contato por WhatsApp, telefone ou e-mail e compartilhe os produtos que você precisa.'], ['2', 'Elaboramos sua proposta', 'Revisamos sua solicitação e preparamos um orçamento personalizado de acordo com seus requisitos.'], ['3', 'Coordenamos seu pedido', 'Uma vez aceito o orçamento, coordenamos com você a entrega ou coleta dos produtos na data acordada.']] },
  contact: { eyebrow: 'Contate-nos', title: 'Solicite informações ou um ', titleEmphasis: 'orçamento', lede: 'Deixe-nos seus dados e entraremos em contato com você para atender sua solicitação.', email: 'E-mail', phone: 'Telefone e WhatsApp', attention: 'Atendimento', attentionInfo: 'Empresas, indústrias, comércios e instituições', form: { nameLabel: 'Nome', emailLabel: 'E-mail', companyLabel: 'Empresa', messageLabel: 'Mensagem', submitButton: 'Enviar solicitação' } },
  newsletter: { title: 'Inscreva-se!', lede: 'Registre-se em nossa newsletter e seja o primeiro a saber sobre nossos lançamentos e promoções', placeholder: 'E-mail', ariaLabelInput: 'E-mail para se inscrever em nossa newsletter', ariaLabelButton: 'Inscrever-se na newsletter', alreadySubscribed: 'Este e-mail já está inscrito em nossa newsletter.', subscriptionSuccess: 'Pronto! Você se inscreveu com sucesso.', subscriptionError: 'Não conseguimos completar sua inscrição. Tente novamente.', networkError: 'Não conseguimos nos conectar ao servidor. Tente novamente em alguns segundos.' },
  chatbot: { openButtonLabel: 'Abrir chatbot', closeButtonLabel: 'Fechar chatbot', headerTitle: 'Assistente Var San', headerSubtitle: 'Orientação sobre produtos e contato', greeting: 'Olá. Sou o Assistente Var San. Posso orientar você sobre nossas linhas de produtos, catálogos, cobertura de entrega e formas de contato. Como podemos ajudar?', inputPlaceholder: 'Escreva sua pergunta (Enter para enviar, Shift+Enter para quebra de linha)', inputAriaLabel: 'Pergunta para o assistente', sendButtonLabel: 'Enviar pergunta', quickProducts: 'Quais produtos vocês oferecem?', quickQuote: 'Solicitar orçamento', quickSupport: 'Atendimento', quickContact: 'Como posso entrar em contato?', loadingMessage: 'Digitando...', errorMessage: 'Não conseguimos processar sua mensagem. Tente novamente em alguns segundos.' },
  footer: { navigationHeading: 'Navegação', contactHeading: 'Contato', requestQuote: 'Solicitar orçamento', rightsReserved: '© {year} Distribuidora Var San. Todos os direitos reservados. |', tagline: 'Soluções de limpeza e proteção para sua empresa.', privacyNotice: 'Aviso de Privacidade', cookiesPolicy: 'Política de Cookies', termsAndConditions: 'Termos e Condições', brandDescription: 'Soluções de limpeza e proteção', footerTagline: 'Soluções de limpeza e proteção para sua empresa. Comprometidos em fornecer soluções confiáveis em limpeza, manutenção e proteção para empresas, comércios e instituições.' },
  splash: { ariaLabel: 'Carregando Distribuidora Var San', tagline: 'Qualidade e confiança em cada fornecimento.' },
};

export default pt;
