import type { Dictionary } from '../types';

const zhCN: Dictionary = {
  nav: { inicio: '首页', esencia: '品牌理念', familia: '我们的团队', soluciones: '解决方案', eleccion: '为何选择我们', impulsamos: '我们的推动力', marcas: '品牌', atencion: '客户服务', contacto: '联系我们', solicitarCotizacion: '索取报价', portalClientes: '客户专区', iniciarSesion: '登录', crearCuenta: '创建账号', miCuenta: '我的账户', abrirMenu: '打开菜单', cerrarMenu: '关闭菜单', navegacionPrincipal: '主要导航' },
  languageSelector: { label: '选择语言' },
  common: { close: '关闭', closeProfileAria: '关闭个人资料', previous: '上一个', next: '下一个', loading: '加载中...' },
  cookies: { ariaLabel: 'Cookie 偏好设置', text: '亲爱的访客，我们使用 Cookie 来改善您的浏览体验。继续使用本网站即表示您同意使用 Cookie。您可以查阅我们的{privacidad}和{cookies}。', privacyLink: '隐私政策', cookiesLink: 'Cookie 政策', accept: '接受', reject: '拒绝' },
  account: { portalTitle: '客户专区', loginTitle: '登录账号', registerTitle: '创建您的账号', loginIntro: '登录您的 Distribuidora Var San 账号。', registerIntro: '注册以使用 Var San 客户专区。', tabLogin: '登录', tabRegister: '创建账号', fieldName: '姓名', fieldNamePlaceholder: '您的姓名', fieldCompany: '公司', fieldCompanyPlaceholder: '您的公司名称', fieldEmail: '电子邮箱', fieldEmailPlaceholder: 'email@company.com', fieldPassword: '密码', fieldPasswordPlaceholderLogin: '您的密码', fieldPasswordPlaceholderRegister: '至少 6 个字符', fieldConfirmPassword: '确认密码', fieldConfirmPasswordPlaceholder: '再次输入密码', submitLogin: '登录', submitRegister: '创建账号', continueWithGoogle: '使用 Google 继续', secureAccessNote: 'Var San 客户通过 Firebase Authentication 与 Firestore 提供安全访问。', passwordMismatch: '两次输入的密码不一致。', accountCreated: '账号已成功创建。', loginSuccess: '登录成功。', errorEmailInUse: '该电子邮箱已注册账号。', errorWeakPassword: '密码至少需要 6 个字符。', errorInvalidEmail: '电子邮箱格式无效。', errorInvalidCredential: '电子邮箱或密码不正确。', errorTooManyRequests: '尝试次数过多，请稍后再试。', errorGeneric: 'Firebase：{code} — {message}', errorGoogleSignIn: '无法使用 Google 登录。', errorSaveProfile: '无法保存个人资料。' },
  portal: { eyebrow: '客户专区', welcome: '欢迎{name}。', intro: '您的登录已连接至 Firebase，客户数据由 Firestore 加载。', fieldNameLabel: '姓名', fieldEmailLabel: '电子邮箱', fieldCompanyLabel: '公司', defaultClientName: 'Var San 客户', notSpecified: '未提供', notAvailable: '无法获取', myProfile: '我的资料', logOut: '退出登录', closePortal: '关闭客户专区', profileHeading: '客户资料', profileIntro: '更改内容会保存到您的 Firestore 资料中。', saveChanges: '保存更改', sessionsTitle: '设备与活跃会话', sessionsSubtitle: '管理已登录您账户的设备。', currentDeviceBadge: '此设备（当前会话）', lastActiveLabel: '最近活跃', locationLabel: '位置 / IP', revokeSession: '退出登录', revokeAllOthers: '退出所有其他设备', confirmRevokeAll: '是否退出所有其他设备的登录？', noActiveSessions: '未记录其他活跃会话。', sessionRevokedSuccess: '已成功退出远程会话。', sessionsRevokedAllSuccess: '已成功退出所有其他活跃会话。', loadingSessions: '正在加载活跃会话...', refreshSessions: '刷新会话' },
  hero: { eyebrow: '领先品牌．品质保证', titleLead: '为您的企业提供', titleHighlight: '清洁与防护', titleTail: '解决方案。', textBefore: '', textAfter: '，精心挑选，适用于企业、工业、商店与机构。', productsHighlight: '1000 款产品', extra: '在 Distribuidora Var San，我们相信优质的供应商不仅是交付产品，更带来信任、品质，以及助力企业成长的解决方案。', exploreSolutions: '探索解决方案', requestQuote: '索取报价', imageAlt: '专业清洁与防护用品', captionEyebrow: '您的合作伙伴', captionText: '在清洁、卫生与防护领域。', statTitle: '1000+ 款产品', statSubtitle: '一站式购齐。' },
  essence: { eyebrow: '我们的理念', title: '代表我们的价值观。', lede: '不仅仅是分销产品，我们基于品质、承诺与信任来构建关系。', values: { quality: { title: '品质', description: '我们精心挑选每一件产品，以提供可靠且性能卓越的解决方案。' }, closeness: { title: '亲近', description: '我们在每个订单过程中提供个性化关注与支持。' }, commitment: { title: '承诺', description: '我们以负责任、准时和为您企业量身定制的服务来响应。' }, trust: { title: '信任', description: '我们基于诚实、支持与一致的结果来构建持久的关系。' } } },
  family: { eyebrow: '加入 Var San 家族', title: '当我们的客户成长时，我们也在成长。', subtitle: 'Var San 经验', label: 'Var San 经验', ariaLabel: '查看{slide}经验', slides: [['信任', '今天我们服务从小型企业到寻求可靠供应商来促进增长的公司。'], ['支持', '从第一份报价到每一次交付，我们都在场。'], ['关系', '我们不寻求单一销售。我们寻求与每个客户建立持久的关系。'], ['增长', '当我们的客户成长时，我们知道我们工作做得很好。'], ['欢迎', '感谢您考虑将 Distribuidora Var San 作为您企业的一部分。']] },
  solutions: { eyebrow: '我们的解决方案', title: '为您的企业找到理想的解决方案', lede: '"查看完整目录"按钮将打开所选产品线的 PDF。每个类别（工业安全和医疗用品）都有自己的独立目录。', catalogPart1: '"查看完整目录"按钮将打开所选产品线的 PDF。每个类别（', catalogStrongPart: '工业安全和医疗用品', catalogPart2: '）都有自己的独立目录。', catalogPart3: '', tabListLabel: '产品线', categoriesLabel: '类别', categoriesScreenReader: '产品类别', previousCategory: '上一个类别', nextCategory: '下一个类别', fullCatalog: '查看完整目录' },
  whyChoose: { eyebrow: '为何选择我们？', title: '为何选择 Distribuidora Var San？', lede: '不仅仅是供应商，我们是推动您企业增长的合作伙伴。', ariaLabel: '选择我们的理由', reasonLabel: '查看原因 {number}', previousReason: '上一个原因', nextReason: '下一个原因', reasons: [['广泛的库存', '数千种产品可用，快速响应不同行业的需求。'], ['知名品牌', '我们与享有盛誉的制造商合作，提供可靠且高性能的解决方案。'], ['个性化服务', '我们倾听每个客户的需求，提供定制咨询和解决方案。'], ['可靠的交付', '我们认真对待每份订单，确保您按时收到产品。'], ['全面的解决方案', '从工业安全到医疗用品，我们在一个地方提供企业所需的一切。'], ['长期承诺', '我们致力于基于信任、服务和结果构建持久的关系。']] },
  sectors: { eyebrow: '我们推动的行业', title: '适用于不同行业的企业的 ', titleEmphasis: '专业解决方案。', names: ['企业', '办公室', '商店', '工业', '学校', '医院和诊所', '餐馆', '酒店', '机构', '一般企业'] },
  brands: { eyebrow: '品牌', title: '我们合作的品牌', lede: '我们分销来自因品质和安全而获得认可的制造商的正品。', distributed: '分销品牌' },
  process: { eyebrow: '服务流程', title: '与我们合作是这样', titleEmphasis: '简单', steps: [['1', '请求您的报价', '通过 WhatsApp、电话或电子邮件与我们联系，并分享您需要的产品。'], ['2', '我们准备您的提案', '我们审查您的请求，并根据您的需求准备个性化报价。'], ['3', '我们协调您的订单', '一旦接受报价，我们与您协调按照商定的日期交付或取货。']] },
  contact: { eyebrow: '与我们联系', title: '请求信息或 ', titleEmphasis: '报价', lede: '留下您的信息，我们将与您联系以处理您的请求。', email: '电子邮箱', phone: '电话和 WhatsApp', attention: '客户服务', attentionInfo: '企业、工业、商店和机构', form: { nameLabel: '姓名', emailLabel: '电子邮箱', companyLabel: '公司', messageLabel: '消息', submitButton: '提交请求' } },
  newsletter: { title: '订阅！', lede: '注册我们的通讯，成为首批了解我们新品和促销的人', placeholder: '电子邮箱地址', ariaLabelInput: '订阅我们通讯的电子邮箱地址', ariaLabelButton: '订阅通讯', alreadySubscribed: '此电子邮箱已订阅我们的通讯。', subscriptionSuccess: '完成！您已成功订阅。', subscriptionError: '我们无法完成您的订阅。请重试。', networkError: '我们无法连接到服务器。请在几秒钟后重试。' },
  chatbot: { openButtonLabel: '打开聊天机器人', closeButtonLabel: '关闭聊天机器人', headerTitle: 'Var San 客服助手', headerSubtitle: '产品与联系方式咨询', greeting: '您好，我是 Var San 客服助手。我可以为您介绍我们的产品线、目录、配送范围以及联系方式。请问需要什么帮助？', inputPlaceholder: '请输入您的问题（Enter 发送，Shift+Enter 换行）', inputAriaLabel: '给客服助手的消息', sendButtonLabel: '发送消息', quickProducts: '你们有哪些产品？', quickQuote: '索取报价', quickSupport: '客户服务', quickContact: '如何联系你们？', loadingMessage: '正在输入...', errorMessage: '无法处理您的消息，请稍后再试。' },
  footer: { navigationHeading: '网站导航', contactHeading: '联系我们', requestQuote: '索取报价', rightsReserved: '© {year} Distribuidora Var San。保留所有权利。|', tagline: '为您的企业提供清洁与防护解决方案。', privacyNotice: '隐私政策', cookiesPolicy: 'Cookie 政策', termsAndConditions: '服务条款', brandDescription: '清洁与防护解决方案', footerTagline: '为您的企业提供清洁与防护解决方案。致力于为企业、商店和机构提供可靠的清洁、维护和防护解决方案。' },
  splash: { ariaLabel: '正在加载 Distribuidora Var San', tagline: '每一次供应，都是品质与信任的保证。' },
};

export default zhCN;
