import type { Dictionary } from '../types';

const zhTW: Dictionary = {
  nav: { inicio: '首頁', esencia: '品牌理念', familia: '我們的團隊', soluciones: '解決方案', eleccion: '為何選擇我們', impulsamos: '我們的推動力', marcas: '品牌', atencion: '客戶服務', contacto: '聯絡我們', solicitarCotizacion: '索取報價', portalClientes: '客戶專區', iniciarSesion: '登入', crearCuenta: '建立帳號', miCuenta: '我的帳戶', abrirMenu: '開啟選單', cerrarMenu: '關閉選單', navegacionPrincipal: '主要導覽' },
  languageSelector: { label: '選擇語言' },
  common: { close: '關閉', closeProfileAria: '關閉個人資料', previous: '上一個', next: '下一個', loading: '載入中...' },
  cookies: { ariaLabel: 'Cookie 偏好設定', text: '親愛的訪客，我們使用 Cookie 來改善您的瀏覽體驗。繼續使用本網站即表示您同意使用 Cookie。您可以查閱我們的{privacidad}與{cookies}。', privacyLink: '隱私權政策', cookiesLink: 'Cookie 政策', accept: '接受', reject: '拒絕' },
  account: { portalTitle: '客戶專區', loginTitle: '登入帳號', registerTitle: '建立您的帳號', loginIntro: '登入您的 Distribuidora Var San 帳號。', registerIntro: '註冊以使用 Var San 客戶專區。', tabLogin: '登入', tabRegister: '建立帳號', fieldName: '姓名', fieldNamePlaceholder: '您的姓名', fieldCompany: '公司', fieldCompanyPlaceholder: '您的公司名稱', fieldEmail: '電子郵件', fieldEmailPlaceholder: 'email@company.com', fieldPassword: '密碼', fieldPasswordPlaceholderLogin: '您的密碼', fieldPasswordPlaceholderRegister: '至少 6 個字元', fieldConfirmPassword: '確認密碼', fieldConfirmPasswordPlaceholder: '再次輸入密碼', submitLogin: '登入', submitRegister: '建立帳號', continueWithGoogle: '使用 Google 繼續', secureAccessNote: 'Var San 客戶透過 Firebase Authentication 與 Firestore 提供安全存取。', passwordMismatch: '兩次輸入的密碼不一致。', accountCreated: '帳號已成功建立。', loginSuccess: '登入成功。', errorEmailInUse: '此電子郵件已有帳號。', errorWeakPassword: '密碼至少需要 6 個字元。', errorInvalidEmail: '電子郵件格式無效。', errorInvalidCredential: '電子郵件或密碼不正確。', errorTooManyRequests: '嘗試次數過多，請稍後再試。', errorGeneric: 'Firebase：{code} — {message}', errorGoogleSignIn: '無法使用 Google 登入。', errorSaveProfile: '無法儲存個人資料。' },
  portal: { eyebrow: '客戶專區', welcome: '歡迎{name}。', intro: '您的登入已連結至 Firebase，客戶資料由 Firestore 載入。', fieldNameLabel: '姓名', fieldEmailLabel: '電子郵件', fieldCompanyLabel: '公司', defaultClientName: 'Var San 客戶', notSpecified: '未提供', notAvailable: '無法取得', myProfile: '我的個人資料', logOut: '登出', closePortal: '關閉客戶專區', profileHeading: '客戶資料', profileIntro: '變更會儲存到您的 Firestore 個人資料中。', saveChanges: '儲存變更', sessionsTitle: '裝置與活躍工作階段', sessionsSubtitle: '管理已登入您帳戶的裝置。', currentDeviceBadge: '此裝置（目前工作階段）', lastActiveLabel: '最近活躍', locationLabel: '位置 / IP', revokeSession: '登出', revokeAllOthers: '登出所有其他裝置', confirmRevokeAll: '是否登出所有其他裝置的登入？', noActiveSessions: '未記錄其他活躍工作階段。', sessionRevokedSuccess: '已成功登出遠端工作階段。', sessionsRevokedAllSuccess: '已成功登出所有其他活躍工作階段。', loadingSessions: '正在載入活躍工作階段...', refreshSessions: '重新整理工作階段' },
  hero: { eyebrow: '領導品牌．品質保證', titleLead: '為您的企業提供', titleHighlight: '清潔與防護', titleTail: '解決方案。', textBefore: '', textAfter: '，精心挑選，適用於企業、工業、商店與機構。', productsHighlight: '1000 項產品', extra: '在 Distribuidora Var San，我們相信優質的供應商不只是交付產品，更帶來信任、品質，以及協助您企業成長的解決方案。', exploreSolutions: '探索解決方案', requestQuote: '索取報價', imageAlt: '專業清潔與防護用品', captionEyebrow: '您的合作夥伴', captionText: '在清潔、衛生與防護領域。', statTitle: '1000+ 項產品', statSubtitle: '一站購足。' },
  essence: { eyebrow: '我們的理念', title: '代表我們的價值觀。', lede: '不僅僅是分銷產品，我們基於品質、承諾與信任來構建關係。', values: { quality: { title: '品質', description: '我們精心挑選每一件產品，以提供可靠且性能卓越的解決方案。' }, closeness: { title: '親近', description: '我們在每個訂單過程中提供個性化關注與支持。' }, commitment: { title: '承諾', description: '我們以負責任、準時和為您企業量身定製的服務來響應。' }, trust: { title: '信任', description: '我們基於誠實、支持與一致的結果來構建持久的關係。' } } },
  family: { eyebrow: '加入 Var San 家族', title: '當我們的客戶成長時，我們也在成長。', subtitle: 'Var San 經驗', label: 'Var San 經驗', ariaLabel: '查看{slide}經驗', slides: [['信任', '今天我們服務從小型企業到尋求可靠供應商來促進增長的公司。'], ['支持', '從第一份報價到每一次交付，我們都在場。'], ['關係', '我們不尋求單一銷售。我們尋求與每個客戶建立持久的關係。'], ['成長', '當我們的客戶成長時，我們知道我們工作做得很好。'], ['歡迎', '感謝您考慮將 Distribuidora Var San 作為您企業的一部分。']] },
  solutions: { eyebrow: '我們的解決方案', title: '為您的企業找到理想的解決方案', lede: '"查看完整型錄"按鈕將打開所選產品線的 PDF。每個類別（工業安全和醫療用品）都有自己的獨立型錄。', catalogPart1: '"查看完整型錄"按鈕將打開所選產品線的 PDF。每個類別（', catalogStrongPart: '工業安全和醫療用品', catalogPart2: '）都有自己的獨立型錄。', catalogPart3: '', tabListLabel: '產品線', categoriesLabel: '類別', categoriesScreenReader: '產品類別', previousCategory: '上一個類別', nextCategory: '下一個類別', fullCatalog: '查看完整型錄' },
  whyChoose: { eyebrow: '為何選擇我們？', title: '為何選擇 Distribuidora Var San？', lede: '不僅僅是供應商，我們是推動您企業成長的合作夥伴。', ariaLabel: '選擇我們的理由', reasonLabel: '查看原因 {number}', previousReason: '上一個原因', nextReason: '下一個原因', reasons: [['廣泛的庫存', '數千種產品可用，快速響應不同行業的需求。'], ['知名品牌', '我們與享有盛譽的製造商合作，提供可靠且高性能的解決方案。'], ['個性化服務', '我們傾聽每個客戶的需求，提供定製諮詢和解決方案。'], ['可靠的交付', '我們認真對待每份訂單，確保您按時收到產品。'], ['全面的解決方案', '從工業安全到醫療用品，我們在一個地方提供企業所需的一切。'], ['長期承諾', '我們致力於基於信任、服務和結果構建持久的關係。']] },
  sectors: { eyebrow: '我們推動的行業', title: '適用於不同行業的企業的 ', titleEmphasis: '專業解決方案。', names: ['企業', '辦公室', '商店', '工業', '學校', '醫院和診所', '餐館', '酒店', '機構', '一般企業'] },
  brands: { eyebrow: '品牌', title: '我們合作的品牌', lede: '我們分銷來自因品質和安全而獲得認可的製造商的正品。', distributed: '分銷品牌' },
  process: { eyebrow: '服務流程', title: '與我們合作是這樣', titleEmphasis: '簡單', steps: [['1', '請求您的報價', '通過 WhatsApp、電話或電子郵件與我們聯絡，並分享您需要的產品。'], ['2', '我們準備您的提案', '我們審查您的請求，並根據您的需求準備個性化報價。'], ['3', '我們協調您的訂單', '一旦接受報價，我們與您協調按照商定的日期交付或取貨。']] },
  contact: { eyebrow: '與我們聯絡', title: '請求資訊或 ', titleEmphasis: '報價', lede: '留下您的資訊，我們將與您聯絡以處理您的請求。', email: '電子郵件', phone: '電話和 WhatsApp', attention: '客戶服務', attentionInfo: '企業、工業、商店和機構', form: { nameLabel: '姓名', emailLabel: '電子郵件', companyLabel: '公司', messageLabel: '訊息', submitButton: '提交請求' } },
  newsletter: { title: '訂閱！', lede: '註冊我們的通訊，成為首批了解我們新品和促銷的人', placeholder: '電子郵件地址', ariaLabelInput: '訂閱我們通訊的電子郵件地址', ariaLabelButton: '訂閱通訊', alreadySubscribed: '此電子郵件已訂閱我們的通訊。', subscriptionSuccess: '完成！您已成功訂閱。', subscriptionError: '我們無法完成您的訂閱。請重試。', networkError: '我們無法連線到伺服器。請在幾秒鐘後重試。' },
  chatbot: { openButtonLabel: '開啟聊天機器人', closeButtonLabel: '關閉聊天機器人', headerTitle: 'Var San 客服助理', headerSubtitle: '產品與聯絡方式諮詢', greeting: '您好，我是 Var San 客服助理。我可以為您介紹我們的產品線、型錄、配送範圍以及聯絡方式。請問需要什麼協助？', inputPlaceholder: '請輸入您的問題（Enter 傳送，Shift+Enter 換行）', inputAriaLabel: '給客服助理的訊息', sendButtonLabel: '傳送訊息', quickProducts: '你們有哪些產品？', quickQuote: '索取報價', quickSupport: '客戶服務', quickContact: '如何與你們聯絡？', loadingMessage: '輸入中...', errorMessage: '無法處理您的訊息，請稍後再試一次。' },
  footer: { navigationHeading: '網站導覽', contactHeading: '聯絡我們', requestQuote: '索取報價', rightsReserved: '© {year} Distribuidora Var San。版權所有，不得轉載。|', tagline: '為您的企業提供清潔與防護解決方案。', privacyNotice: '隱私權政策', cookiesPolicy: 'Cookie 政策', termsAndConditions: '服務條款', brandDescription: '清潔與防護解決方案', footerTagline: '為您的企業提供清潔與防護解決方案。致力於為企業、商店和機構提供可靠的清潔、維護和防護解決方案。' },
  splash: { ariaLabel: '正在載入 Distribuidora Var San', tagline: '每一次供應，都是品質與信任的保證。' },
};

export default zhTW;
